### ISSUE TITLE
Misses some buttons on some bars.

### ISSUE THREAD

**Issue by geckzilla** [Pr3vention/UniversalBar#2] opened 2023-12-19 05:45 UTC
Bar 7 and Bar 2 specifically; not all of my buttons are copied. Not sure why. Just seems to put a blank instead of what I copied.

**Comment by Pr3vention** [comment] 2023-12-19 13:41
A few questions to narrow down the issue:

- Are the missing action buttons in the first or last slot of the action bar or somewhere in the middle?
- What kind of action (spell, mounts, macro, etc) is expected in the missing slot?
- Is this happening between all your characters or only between certain classes (e.g. Paladin to Mage, Warlock to Evoker, etc)

**Comment by geckzilla** [comment] 2023-12-19 18:30
Both in the middle and at the end. Like one was button 12 of bar 7, and another was... I'm not sure, 5 or 6 or 7. Maybe all three of those. It's hard to tell which one without a defined keybinding on them. A couple were macros and a couple were gear sets. Now that I think about it, it's probably hard to copy those. And it was happening between specs (Preservation to Augmentation to Devastation).

Anyway it's a good addon, thanks for making it and responding so fast!

**Comment by Pr3vention** [comment] 2023-12-19 19:36
Thank you for the added details. I was thinking the slotID calculation was off for some action bars, but sounds like this is more likely an issue with how some action types are saved or how they are interpreted when attempting to restore them. For example, macros have been difficult to get working right due to how they're exposed in the client. I can reference them with a number but not directly by name, so adding or renaming macros can throw off auto-loading. Items should definitely be working though, so there's clearly a bug there.

Have a few ideas of where this is failing, so will investigate and resolve ASAP. 

While not necessary, if you can provide your SavedVariables file for UniversalBar, that would help me reproduce your exact setup. You should be able to find it in your WoW folder (e.g. `_retail_\WTF\Account\SavedVariables\UniversalBar.lua`).

**Comment by geckzilla** [comment] 2023-12-19 20:12
Sure thing, here you go. I can try saving and loading them again later today to pin down exactly which ones aren't going through. Seems easier to identify them now that I see this lua code. I was having trouble with the in game interface.

`
UniversalBarSettings = {
	["AutosaveSlotChanges"] = true,
	["ClearUnsavedActionSlots"] = true,
	["Bars"] = {
		nil, -- [1]
		true, -- [2]
		true, -- [3]
		true, -- [4]
		true, -- [5]
		true, -- [6]
		false, -- [7]
		true, -- [8]
	},
	["AutoLoadAtLogin"] = true,
	["BarConfig"] = {
		nil, -- [1]
		{
			nil, -- [1]
			{
				["id"] = "Healthstone",
				["type"] = "macro",
			}, -- [2]
			{
				["id"] = 373861,
				["type"] = "spell",
			}, -- [3]
			{
				["id"] = 370553,
				["type"] = "spell",
			}, -- [4]
			nil, -- [5]
			{
				["id"] = 364342,
				["type"] = "spell",
			}, -- [6]
			{
				["type"] = "mount",
			}, -- [7]
			{
				["id"] = 369536,
				["type"] = "spell",
			}, -- [8]
			{
				["id"] = 372608,
				["type"] = "spell",
			}, -- [9]
			{
				["id"] = 361178,
				["type"] = "spell",
			}, -- [10]
			{
				["id"] = 122708,
				["type"] = "mount",
			}, -- [11]
			{
				["id"] = "TMW",
				["type"] = "macro",
			}, -- [12]
		}, -- [2]
		{
			nil, -- [1]
			{
				["id"] = 393276,
				["type"] = "spell",
			}, -- [2]
			{
				["id"] = 424153,
				["type"] = "spell",
			}, -- [3]
			{
				["id"] = 159901,
				["type"] = "spell",
			}, -- [4]
			{
				["id"] = 410074,
				["type"] = "spell",
			}, -- [5]
			{
				["id"] = 393283,
				["type"] = "spell",
			}, -- [6]
			{
				["id"] = 410071,
				["type"] = "spell",
			}, -- [7]
			{
				["id"] = 410078,
				["type"] = "spell",
			}, -- [8]
			{
				["id"] = 410080,
				["type"] = "spell",
			}, -- [9]
			{
				["id"] = 393267,
				["type"] = "spell",
			}, -- [10]
			{
				["id"] = 393222,
				["type"] = "spell",
			}, -- [11]
		}, -- [3]
		{
			{
				["id"] = "PvP ON",
				["type"] = "macro",
			}, -- [1]
			{
				["id"] = "Raid",
				["type"] = "macro",
			}, -- [2]
			{
				["id"] = "Layout",
				["type"] = "macro",
			}, -- [3]
			nil, -- [4]
			nil, -- [5]
			nil, -- [6]
			{
				["id"] = 131474,
				["type"] = "spell",
			}, -- [7]
			{
				["id"] = 153039,
				["type"] = "toy",
			}, -- [8]
			{
				["id"] = 2550,
				["type"] = "spell",
			}, -- [9]
			{
				["id"] = 193290,
				["type"] = "spell",
			}, -- [10]
			{
				["id"] = 45357,
				["type"] = "spell",
			}, -- [11]
			{
				["id"] = 83958,
				["type"] = "spell",
			}, -- [12]
		}, -- [4]
		{
			[11] = {
				["id"] = 205255,
				["type"] = "toy",
			},
			[12] = {
				["id"] = 65274,
				["type"] = "item",
			},
			[4] = {
				["id"] = 110560,
				["type"] = "toy",
			},
			[5] = {
				["id"] = 140192,
				["type"] = "toy",
			},
			[6] = {
				["id"] = 162973,
				["type"] = "toy",
			},
		}, -- [5]
		{
			nil, -- [1]
			{
				["id"] = 198617,
				["type"] = "item",
			}, -- [2]
			{
				["id"] = 194885,
				["type"] = "toy",
			}, -- [3]
			{
				["id"] = 211495,
				["type"] = "item",
			}, -- [4]
			{
				["id"] = 113509,
				["type"] = "item",
			}, -- [5]
			{
				["id"] = 197771,
				["type"] = "item",
			}, -- [6]
			{
				["id"] = 191389,
				["type"] = "item",
			}, -- [7]
			{
				["id"] = 204973,
				["type"] = "item",
			}, -- [8]
			{
				["id"] = 191364,
				["type"] = "item",
			}, -- [9]
			{
				["id"] = 191341,
				["type"] = "item",
			}, -- [10]
			{
				["id"] = 204072,
				["type"] = "item",
			}, -- [11]
			{
				["id"] = 191395,
				["type"] = "item",
			}, -- [12]
		}, -- [6]
		{
			{
				["id"] = 351239,
				["type"] = "spell",
			}, -- [1]
			nil, -- [2]
			{
				["id"] = "Aug",
				["type"] = "macro",
			}, -- [3]
			{
				["id"] = "Devas",
				["type"] = "macro",
			}, -- [4]
			{
				["id"] = "Pres",
				["type"] = "macro",
			}, -- [5]
			{
				["id"] = 390386,
				["type"] = "spell",
			}, -- [6]
			{
				["id"] = "LANG",
				["type"] = "macro",
			}, -- [7]
			[10] = {
				["id"] = "Devastation",
				["type"] = "equipmentset",
			},
			[11] = {
				["id"] = "Preservation",
				["type"] = "equipmentset",
			},
		}, -- [7]
		{
			nil, -- [1]
			{
				["id"] = 193033,
				["type"] = "toy",
			}, -- [2]
			{
				["id"] = 187840,
				["type"] = "toy",
			}, -- [3]
			{
				["id"] = 205688,
				["type"] = "toy",
			}, -- [4]
			{
				["id"] = 205418,
				["type"] = "toy",
			}, -- [5]
			{
				["id"] = 201927,
				["type"] = "toy",
			}, -- [6]
			{
				["id"] = 194052,
				["type"] = "toy",
			}, -- [7]
			{
				["id"] = 166701,
				["type"] = "toy",
			}, -- [8]
			{
				["id"] = 88589,
				["type"] = "toy",
			}, -- [9]
			{
				["id"] = 206268,
				["type"] = "toy",
			}, -- [10]
			{
				["id"] = 49703,
				["type"] = "toy",
			}, -- [11]
			{
				["id"] = 190333,
				["type"] = "toy",
			}, -- [12]
		}, -- [8]
	},
}
`

**Comment by geckzilla** [comment] 2023-12-19 20:13
oh good grief I should have previewed that. here's an attached file renamed to .txt
[UniversalBar.lua.txt](https://github.com/Pr3vention/UniversalBar/files/13719942/UniversalBar.lua.txt)

**Comment by geckzilla** [comment] 2023-12-19 20:16
I can tell you, from memory, it did copy the "TMW" macro and also the "LANG" macro, but not the fishing macro... ugh, that's not in the file, i must have taken the bar off.. sorry, I gotta go to an appointment soon I'll reupload later. This is what I get for trying to do this in a rush

**Comment by Pr3vention** [comment] 2023-12-20 02:37
Version 1.1.0 should be available through Wago, Curseforge and WoWInterface shortly to address the issue with equipment sets. After reviewing the content of your settings and running some tests, I was unable to reproduce any issue with items or macros. Give this new version a shot and let me know if it works for you!

**Comment by geckzilla** [comment] 2023-12-20 19:56
Thanks for the update. It's already saved me so much time as is.

Equipment sets are now loading. Some macros are now loading while others are not. Like, at BarConfig[1][0] it is recording a nil when there is a macro there. also [1][4] is a macro. [1][6] is a "Summon random favorite mount" button (the mount with no respective ID)

I think bar 6 might be offset by one. It's recording the gear set at [11] but it's actually in the 10th position on the bar when starting at 0. I've got a macro at position 11, but it correctly puts the two gear sets into the 9th and 10th buttons while ignoring the macro. Not 100% sure on this one.

**Comment by Pr3vention** [comment] 2023-12-21 04:19
The favorite mount action should be fixed in the next release.

I've checked every bar and verified the slotIDs are correct as of client build 10.2.0.52649 so I don't think it's an off-by-one error, but I can't rule out something weird having happened when saving your bars. I recommend hitting the "Save Bars" button in settings to take a new snapshot of your configuration, then see if you can reproduce it. If you can, a picture of your action bars and a new copy of your UniversalBar settings would be helpful.

Ran out of time tonight to work on this more, but will continue when I return from work tomorrow.

**Comment by Pr3vention** [comment] 2024-05-17 19:17
Closing this issue as it's been inactive for several months with no ability to reproduce. If you continue to experience a problem, please open a new issue and provide new details.

**Closed by Pr3vention** 2024-05-17 19:17 UTC
Labels: bug
